### ISSUE TITLE
Cross Region / Intrusion not working.

### ISSUE THREAD

**Issue by TheDukeSr** [rroller/dahua#37]
## Version of the custom_component
V0.8.7

Option in Dahua integration for cross region (and more) detection is enabled.

## Describe the bug
Intrusion region detection does not trigger in Hass (but it does trigger in camera app/browser when tested).
Event listener in Hass dev "dahua_event_received" does also NOT get triggered.
Is there another "event listener" I need to use?

ps. Cross line, and Motion do trigger OK.

**Logs:**
Debug ON, Nothing in the logfiles.

[Camera intrusion config screenprint](https://photos.app.goo.gl/xpyTCrdcy9PB3E5T7)
 
[Activated options in Dahua integration screenshot](https://photos.app.goo.gl/LJ44dRQRts2r3s63A)

**Comment by rroller** [comment]
I can't get this to even trigger on the cams. I've completely been unable to get this to fire an event for Cross Region Detection. The camera never sends the events. I spent a lot of time and fiddling with a few cameras and never got the event to fire. If you are able to figure out how to make it fire, please let me know.

**Comment by TheDukeSr** [comment]
I'll give it a try. Just need a few days and will let you know the result..

**Comment by rroller** [comment]
FYI, I've updated the readme on how to use events

https://github.com/rroller/dahua/blob/main/README.md#events

**Comment by TheDukeSr** [comment]
Can you do something with this Wireshark capture?
ps. I have more if you want it.

```
<script>var json={"id":77,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Stop","Code":"CrossRegionDetection","Data":{"Action":"Appear","Class":"Normal","CountInGroup":1,"DetectRegion":[[3299,1365],[796,7308],[7918,7589],[8123,522]],"EventSeq":2,"FrameSequence":18326290,"GroupID":2,"IndexInGroup":0,"LocaleTime":"2021-07-02 05:18:35","Mark":0,"Name":"Rule1","Object":{"Action":"Appear","BoundingBox":[5504,2368,5840,3008],"Center":[5672,2688],"Confidence":0,"FrameSequence":0,"LowerBodyColor":[0,0,0,0],"MainColor":[0,0,0,0],"ObjectID":45,"ObjectType":"Human","RelativeID":0,"Source":0.0,"Speed":0,"SpeedTypeInternal":0},"PTS":43316123430.0,"RuleId":1,"Sequence":0,"Source":33188816.0,"Track":null,"UTC":1625203112,"UTCMS":255},"Index":0}]},"session":"727389a9cf052a9cfc963cbfd0c9c429"}
parent.receiveMessage(json);</script>
```

**Comment by TheDukeSr** [comment]
Looks like API just isn't there. Crossdetection is not included.
I'm very busy the next week, so I need a lot more time before I can do something with SNMP.
Maybe close this one as not solved? and I'll keep you informed when I get some results later.

**Comment by rroller** [comment]
Yeah I can't find it either. I'll resolve the issue. Feel free to open it up if you find a way to solve this. Thanks!
