### ISSUE TITLE
Home Assistant 2021.9.x enhancements

### ISSUE THREAD

**Issue by mstefany** [rroller/dahua#84]
Home Assistant 2021.9.0 introduced some breaking changes to camera integrations:
https://www.home-assistant.io/blog/2021/09/01/release-20219/#breaking-changes

Core PR: https://github.com/home-assistant/core/pull/53835

```
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Kamera (documentation, issues)
First occurred: 11:22:26 (7 occurrences)
Last logged: 11:22:26

The camera entity camera.frontyard2_main does not support requesting width and height, please open an issue with the integration author
The camera entity camera.frontyard1_sub does not support requesting width and height, please open an issue with the integration author
```

**Comment by rroller** [comment]
Thanks, looking into this

**Comment by rroller** [comment]
Fixed in https://github.com/rroller/dahua/releases/tag/0.9.23

**Comment by maxoss** [comment]
Seems to be that i've still have this issue. https://github.com/rroller/dahua/issues/86

**Comment by rroller** [comment]
This was fixed in in This was fixed in 0.9.24. Please update to that version. Thanks!

https://github.com/rroller/dahua/issues/86
